# Objectives
After completing this lab you will be able to:

* Operate comfortably with numpy
* Perform complex operations with numpy

## Create a 2D Numpy Array

In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

Consider the list a, which contains three nested lists each of equal size.

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a Numpy Array as follows:

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute ndim to obtain the number of axes or dimensions, referred to as the rank.

In [4]:
# Show the numpy array dimensions

A.ndim

2

Attribute shape returns a tuple corresponding to the size or number of each dimension.

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

The total number of elements in the array is given by the attribute size.

In [6]:
# Show the numpy array size

A.size

9

## Accessing different elements of a Numpy Array
We simply use the square brackets and the indices corresponding to the element we would like:

In [7]:
# Access the element on the second row and third column

A[1, 2]

23

We can also use the following notation to obtain the elements:

In [8]:
# Access the element on the second row and third column

A[1][2]

23

We can access the element as follows:

In [9]:
# Access the element on the first row and first column

A[0][0]

11

We can also use slicing in numpy arrays.

This can be done with the following syntax:

In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:

In [12]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

## Basic Operations
We can also add arrays. The process is identical to matrix addition.

The numpy array is given by X and Y

In [13]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [14]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

We can add the numpy arrays as follows.

In [15]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix Y by the scaler 2, we simply multiply every element in the matrix by 2.

We can perform the same operation in numpy as follows



In [16]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [17]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix Y or X.

We can perform element-wise product of the array X and Y as follows:

In [18]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [20]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays A and B as follows:

First, we define matrix A and B:

In [21]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [22]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function dot to multiply the arrays together.

In [23]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [24]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute T to calculate the transposed matrix

In [25]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [26]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

## Quiz on 2D Numpy Array
Consider the following list a, convert it to Numpy Array.

In [27]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the numpy array size.

In [28]:
# Write your code below and press Shift+Enter to execute
A.size

12

Access the element on the first row and first and second columns.

In [29]:
# Write your code below and press Shift+Enter to execute
A[0,0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays A and B.

In [30]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
Z = np.dot(A,B)
Z

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])